### PR TITLE
BlueMaestro

### PR DESCRIPTION
**Pull request by ukBaz**
This is not for merging!

I am looking for some feedback on implementing a new device/packet structure.
I have recently purchased the BlueMaestro Pebble Environment Monitor that has the following packet structure
https://www.bluemaestro.com/interpret-bluetooth-advertisement-packet/

Is how I’ve started implementing this inline with what you would expect for a new plugin?

### CODE REVIEW

**Comment by frawau** [comment]
Thanks for your interest in aioblescan.

I am currently travelling, I'll have a look at your issue as soon as I can

**Comment by frawau** [comment]
Looks good to me.

Will you also need to send that "Scan Request" command?

**Comment by ukBaz** [comment]
There does seem to be more data available if I can send a scan response request but I haven't worked out how to do that yet. Any ideas?

**Comment by frawau** [comment]
Thanks for the pull request. And sorry for waiting so long to merge it. I totally missed this

**Pull request merged**
