### PR TITLE
Add support for ThermoBeacon temperature and humidity sensors

### PR DESCRIPTION
**Pull request by 8none1**
This PR adds support for BTLE ThermoBeacon devices sometimes called ORIA.

AliExpress link here:  https://www.aliexpress.com/item/1005001792309115.html?spm=a2g0s.9042311.0.0.7fac4c4dTTFobz

I pretty much cloned the ATC way of doing things.

I'm not a great Python developer, so I'll happily make changes given suggestions and advice.

I'm also not thrilled about using the uppercase T command line option, but it seemed to be the best option.

I have updated the README files etc.

Thanks for working on a very handy project.

### CODE REVIEW

**Comment by 8none1** [comment]
Just a quick comment to say this has been running "in production" for a week at my house and is working well.

**Review by frawau — APPROVED** [review]
Seems pretty straightforward.

**Comment by frawau** [comment]
Thanks for the PR. Sorry, I was pretty busy last week, had not noticed it.  Will test things out a bit, then will release. One question, what are the "_ts" values?

**Comment by 8none1** [comment]
As far as I can tell the `max_temp_ts` and `min_temp_ts` are the counter time that the min and max temperatures were seen.  I haven't found the min & max information to be terribly useful to be honest. Perhaps that could be commented out?

I record the information continually to InfluxDB - perhaps if I read the information once in a while it would be more useful?  Perhaps best left as an exercise for the user?  I can add something to the readme if it will help?


Thanks for merging!

**Pull request merged**
