### PR TITLE
Decode ATC_MiThermometer packets

### PR DESCRIPTION
**Pull request by jjtt**
I'm playing with these: https://github.com/atc1441/ATC_MiThermometer

And your project looked like a good fit so I created a simple class to decode those messages.

This is very much a work in progress, but since it does already report the temperature I thought you might accept my humble contribution.

### CODE REVIEW

**Comment by MS3FGX** [comment]
Seems to work fine with my thermometers running the ATC firmware, but why not display the MAC address? Otherwise, the data from multiple sensors will just get jumbled together.

**Comment by jjtt** [comment]
> but why not display the MAC address?

Good point. I'm hoping I would have realised that myself also once trying to actually do something with this.

**Comment by MS3FGX** [comment]
Just confirming that the latest version is working as expected for me, I see my three sensors with their correct MAC addresses listed.

**Comment by lolren** [comment]
Can someone make a small tutorial of how to use it with the ATC firmware? I cannot get it to work. Regards

**Comment by frawau** [comment]
I am sorry for the delay. I did miss your PR completely.

I'll check things tomorrow.

**Comment by 8none1** [comment]
I've been running this plugin for a few weeks, and it seems to work fine. Thanks!

**Comment by frawau** [comment]
Thanks.

**Comment by frawau** [comment]
I just released a new version with your plugin included.

Thanks again... and sorry for the delay

**Comment by frawau** [comment]
Hi, I am about to release a new version. Would it be possible to check if it messes up with your plugin? I plan to release it on Wed 19 May 2021 around 19:00 GMT

TIA

**Pull request merged**
